### ISSUE TITLE
Python XPath SyntaxError: invalid predicate when using paloaltonetworks.panos.panos_software task

### ISSUE THREAD

**Issue by pkleanthous** [PaloAltoNetworks/pan-os-ansible#155]
## Describe the bug

The `paloaltonetworks.panos.panos_software` task fails due to Python XPath SyntaxError: invalid predicate 

## Expected behavior

The task should work

## Current behavior

Error Message

```
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/xml/etree/ElementPath.py", line 263, in iterfind
    selector = _cache[cache_key]
KeyError: ('./result/sw-updates/versions/entry/version[.="10.0.2"]/../downloaded', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/kokos/.ansible/tmp/ansible-tmp-1605255165.3774896-2043-255234810372041/AnsiballZ_panos_software.py", line 102, in <module>
    _ansiballz_main()
  File "/kokos/.ansible/tmp/ansible-tmp-1605255165.3774896-2043-255234810372041/AnsiballZ_panos_software.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/kokos/.ansible/tmp/ansible-tmp-1605255165.3774896-2043-255234810372041/AnsiballZ_panos_software.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.paloaltonetworks.panos.plugins.modules.panos_software', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_paloaltonetworks.panos.panos_software_payload_3vsdid91/ansible_paloaltonetworks.panos.panos_software_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_software.py", line 188, in <module>
  File "/tmp/ansible_paloaltonetworks.panos.panos_software_payload_3vsdid91/ansible_paloaltonetworks.panos.panos_software_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_software.py", line 165, in main
  File "/usr/lib64/python3.6/xml/etree/ElementPath.py", line 311, in findtext
    elem = next(iterfind(elem, path, namespaces))
  File "/usr/lib64/python3.6/xml/etree/ElementPath.py", line 277, in iterfind
    selector.append(ops[token[0]](next, token))
  File "/usr/lib64/python3.6/xml/etree/ElementPath.py", line 233, in prepare_predicate
    raise SyntaxError("invalid predicate")
SyntaxError: invalid predicate
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/usr/lib64/python3.6/xml/etree/ElementPath.py\", line 263, in iterfind\n    selector = _cache[cache_key]\nKeyError: ('./result/sw-updates/versions/entry/version[.=\"10.0.2\"]/../downloaded', None)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/kokos/.ansible/tmp/ansible-tmp-1605255165.3774896-2043-255234810372041/AnsiballZ_panos_software.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/kokos/.ansible/tmp/ansible-tmp-1605255165.3774896-2043-255234810372041/AnsiballZ_panos_software.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/kokos/.ansible/tmp/ansible-tmp-1605255165.3774896-2043-255234810372041/AnsiballZ_panos_software.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.paloaltonetworks.panos.plugins.modules.panos_software', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_paloaltonetworks.panos.panos_software_payload_3vsdid91/ansible_paloaltonetworks.panos.panos_software_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_software.py\", line 188, in <module>\n  File \"/tmp/ansible_paloaltonetworks.panos.panos_software_payload_3vsdid91/ansible_paloaltonetworks.panos.panos_software_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_software.py\", line 165, in main\n  File \"/usr/lib64/python3.6/xml/etree/ElementPath.py\", line 311, in findtext\n    elem = next(iterfind(elem, path, namespaces))\n  File \"/usr/lib64/python3.6/xml/etree/ElementPath.py\", line 277, in iterfind\n    selector.append(ops[token[0]](next, token))\n  File \"/usr/lib64/python3.6/xml/etree/ElementPath.py\", line 233, in prepare_predicate\n    raise SyntaxError(\"invalid predicate\")\nSyntaxError: invalid predicate\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

## Steps to reproduce

Use the following task
```
- name: "Update to latest SW version"
  paloaltonetworks.panos.panos_software:
    provider: "{{ provider }}"
    version: "10.0.2"
    restart: true
```

## Your Environment

Ansible
```
ansible --version
ansible 2.10.2
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /root/.local/lib/python3.6/site-packages/ansible
  executable location = /root/.local/bin/ansible
  python version = 3.6.8 (default, Apr  2 2020, 13:34:55) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

ansible-galaxy collection list 

```
ansible-galaxy collection list  

# /kokos/.ansible/collections/ansible_collections
Collection             Version
---------------------- -------
amazon.aws             1.2.1  
ansible.netcommon      1.4.1  
community.aws          1.2.1  
paloaltonetworks.panos 2.2.0  
```

**Comment by pkleanthous** [comment]
I have switched back to `2.1.0` version and the task works as expected.
