### ISSUE TITLE
`ValueError: No param "type" exists` in `panos_custom_url_category` (`...pandevice/base.py", line 2206`)

### ISSUE THREAD

**Issue by jgspratt** [PaloAltoNetworks/pan-os-ansible#284]
## Describe the bug

`panos_custom_url_category` fails to execute, throwing `ValueError: No param "type" exists`

## Steps to reproduce

```
---
- name: "manage palo alto"
  hosts: localhost
  gather_facts: false
  collections:
    - paloaltonetworks.panos
  tasks:
    - name: set palo provider
      set_fact:
        palo_provider:
          [REDACTED]

    - name: Create test URL category
      panos_custom_url_category:
        type: URL List
        provider: "{{ palo_provider }}"
        name: test-api-list
        description: test-api-list
        url_value:
          - www.example.com
          - www2.example.com
```

```
> ansible-playbook palo.yml -vvv
ansible-playbook 2.9.26
  config file = None
  configured module search path = ['/Users/jgspratt/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.9.9 (main, Nov 21 2021, 03:22:47) [Clang 12.0.0 (clang-1200.0.32.29)]
No config file found; using defaults
host_list declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
script declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
yaml declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
ini declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
toml declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
Skipping callback 'actionable', as we already have a stdout callback.
Skipping callback 'counter_enabled', as we already have a stdout callback.
Skipping callback 'debug', as we already have a stdout callback.
Skipping callback 'dense', as we already have a stdout callback.
Skipping callback 'dense', as we already have a stdout callback.
Skipping callback 'full_skip', as we already have a stdout callback.
Skipping callback 'json', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'null', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.
Skipping callback 'selective', as we already have a stdout callback.
Skipping callback 'skippy', as we already have a stdout callback.
Skipping callback 'stderr', as we already have a stdout callback.
Skipping callback 'unixy', as we already have a stdout callback.
Skipping callback 'yaml', as we already have a stdout callback.

PLAYBOOK: palo.yml ************************************************************************************************************************************
1 plays in palo.yml

PLAY [manage palo alto] *******************************************************************************************************************************
META: ran handlers

TASK [set palo provider] ******************************************************************************************************************************
task path: /Users/jgspratt/git/[REDACTED]/ansible-test/palo.yml:8
ok: [localhost] => {
    "ansible_facts": {
        "palo_provider": {
          [REDACTED]
        }
    },
    "changed": false
}

TASK [Create test URL category] ***********************************************************************************************************************
task path: /Users/jgspratt/git/[REDACTED]/ansible-test/palo.yml:15
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: jgspratt
<127.0.0.1> EXEC /bin/sh -c 'echo ~jgspratt && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/jgspratt/.ansible/tmp `"&& mkdir "` echo /Users/jgspratt/.ansible/tmp/ansible-tmp-1639413561.205141-43035-44359104565286 `" && echo ansible-tmp-1639413561.205141-43035-44359104565286="` echo /Users/jgspratt/.ansible/tmp/ansible-tmp-1639413561.205141-43035-44359104565286 `" ) && sleep 0'
Using module file /Users/jgspratt/.ansible/collections/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_custom_url_category.py
<127.0.0.1> PUT /Users/jgspratt/.ansible/tmp/ansible-local-43026yt18o6j0/tmp0bwrb04k TO /Users/jgspratt/.ansible/tmp/ansible-tmp-1639413561.205141-43035-44359104565286/AnsiballZ_panos_custom_url_category.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /Users/jgspratt/.ansible/tmp/ansible-tmp-1639413561.205141-43035-44359104565286/ /Users/jgspratt/.ansible/tmp/ansible-tmp-1639413561.205141-43035-44359104565286/AnsiballZ_panos_custom_url_category.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/local/opt/python@3.9/bin/python3.9 /Users/jgspratt/.ansible/tmp/ansible-tmp-1639413561.205141-43035-44359104565286/AnsiballZ_panos_custom_url_category.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /Users/jgspratt/.ansible/tmp/ansible-tmp-1639413561.205141-43035-44359104565286/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/Users/jgspratt/.ansible/tmp/ansible-tmp-1639413561.205141-43035-44359104565286/AnsiballZ_panos_custom_url_category.py", line 102, in <module>
    _ansiballz_main()
  File "/Users/jgspratt/.ansible/tmp/ansible-tmp-1639413561.205141-43035-44359104565286/AnsiballZ_panos_custom_url_category.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/Users/jgspratt/.ansible/tmp/ansible-tmp-1639413561.205141-43035-44359104565286/AnsiballZ_panos_custom_url_category.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.paloaltonetworks.panos.plugins.modules.panos_custom_url_category', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 210, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/var/folders/h9/w3s8_3091s58lm8xbnbrp2m80000gn/T/ansible_panos_custom_url_category_payload_vroz8z17/ansible_panos_custom_url_category_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_custom_url_category.py", line 151, in <module>
  File "/var/folders/h9/w3s8_3091s58lm8xbnbrp2m80000gn/T/ansible_panos_custom_url_category_payload_vroz8z17/ansible_panos_custom_url_category_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_custom_url_category.py", line 143, in main
  File "/usr/local/lib/python3.9/site-packages/pandevice/base.py", line 2206, in __init__
    raise ValueError('No param "{0}" exists'.format(name))
ValueError: No param "type" exists
fatal: [localhost]: FAILED! => {
    "changed": false,
    "rc": 1
}

MSG:

MODULE FAILURE
See stdout/stderr for the exact error


MODULE_STDERR:

Traceback (most recent call last):
  File "/Users/jgspratt/.ansible/tmp/ansible-tmp-1639413561.205141-43035-44359104565286/AnsiballZ_panos_custom_url_category.py", line 102, in <module>
    _ansiballz_main()
  File "/Users/jgspratt/.ansible/tmp/ansible-tmp-1639413561.205141-43035-44359104565286/AnsiballZ_panos_custom_url_category.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/Users/jgspratt/.ansible/tmp/ansible-tmp-1639413561.205141-43035-44359104565286/AnsiballZ_panos_custom_url_category.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.paloaltonetworks.panos.plugins.modules.panos_custom_url_category', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 210, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/var/folders/h9/w3s8_3091s58lm8xbnbrp2m80000gn/T/ansible_panos_custom_url_category_payload_vroz8z17/ansible_panos_custom_url_category_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_custom_url_category.py", line 151, in <module>
  File "/var/folders/h9/w3s8_3091s58lm8xbnbrp2m80000gn/T/ansible_panos_custom_url_category_payload_vroz8z17/ansible_panos_custom_url_category_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_custom_url_category.py", line 143, in main
  File "/usr/local/lib/python3.9/site-packages/pandevice/base.py", line 2206, in __init__
    raise ValueError('No param "{0}" exists'.format(name))
ValueError: No param "type" exists


PLAY RECAP ********************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

## Your Environment

```
MacOS 10.15.7 (19H1519)
```

```
pip3 install ansible==2.9.26 # Successfully installed MarkupSafe-2.0.1 PyYAML-6.0 ansible-2.9.26 cffi-1.15.0 cryptography-36.0.0 jinja2-3.0.3 pycparser-2.21
pip3 install pan-python # Successfully installed pan-python-0.16.0
pip3 install pandevice # Successfully installed pandevice-0.14.0
ansible-galaxy collection install paloaltonetworks.panos # Installing 'paloaltonetworks.panos:2.9.0' to '/Users/jgspratt/.ansible/collections/ansible_collections/paloaltonetworks/panos'
```

```
      Model Name: MacBook Pro
      Model Identifier: MacBookPro16,1
      Processor Name: 8-Core Intel Core i9
      Processor Speed: 2.4 GHz
      Number of Processors: 1
      Total Number of Cores: 8
      L2 Cache (per Core): 256 KB
      L3 Cache: 16 MB
      Hyper-Threading Technology: Enabled
      Memory: 64 GB
      Boot ROM Version: 1715.40.15.0.0 (iBridge: 19.16.10549.0.0,0)
```

**Comment by jgspratt** [comment]
Same result testing again after upgrading to Ansible 2.10.7 (after full uninstall/re-install including removing and re-installing the Galaxy Collection):

```
ansible-playbook 2.10.16
  config file = None
  configured module search path = ['/Users/jgspratt/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.9.9 (main, Nov 21 2021, 03:22:47) [Clang 12.0.0 (clang-1200.0.32.29)]
No config file found; using defaults
host_list declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
script declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
yaml declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
ini declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
toml declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
redirecting (type: callback) ansible.builtin.debug to ansible.posix.debug
redirecting (type: callback) ansible.builtin.debug to ansible.posix.debug
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: palo.yml ************************************************************************************************************************************
1 plays in palo.yml

PLAY [manage palo alto] *******************************************************************************************************************************
META: ran handlers

TASK [set palo provider] ******************************************************************************************************************************
task path: /Users/jgspratt/git/jgs/lowside/scratch/ansible-test/palo.yml:8
ok: [localhost] => {
    "ansible_facts": {
        "palo_provider": {
          [REDACTED]
        }
    },
    "changed": false
}

TASK [Create test URL category] ***********************************************************************************************************************
task path: /Users/jgspratt/git/jgs/lowside/scratch/ansible-test/palo.yml:15
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: jgspratt
<127.0.0.1> EXEC /bin/sh -c 'echo ~jgspratt && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/jgspratt/.ansible/tmp `"&& mkdir "` echo /Users/jgspratt/.ansible/tmp/ansible-tmp-1639417104.2653282-67262-100139011685712 `" && echo ansible-tmp-1639417104.2653282-67262-100139011685712="` echo /Users/jgspratt/.ansible/tmp/ansible-tmp-1639417104.2653282-67262-100139011685712 `" ) && sleep 0'
Using module file /Users/jgspratt/.ansible/collections/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_custom_url_category.py
<127.0.0.1> PUT /Users/jgspratt/.ansible/tmp/ansible-local-672538yz61c2p/tmp2hmehftd TO /Users/jgspratt/.ansible/tmp/ansible-tmp-1639417104.2653282-67262-100139011685712/AnsiballZ_panos_custom_url_category.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /Users/jgspratt/.ansible/tmp/ansible-tmp-1639417104.2653282-67262-100139011685712/ /Users/jgspratt/.ansible/tmp/ansible-tmp-1639417104.2653282-67262-100139011685712/AnsiballZ_panos_custom_url_category.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/local/opt/python@3.9/bin/python3.9 /Users/jgspratt/.ansible/tmp/ansible-tmp-1639417104.2653282-67262-100139011685712/AnsiballZ_panos_custom_url_category.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /Users/jgspratt/.ansible/tmp/ansible-tmp-1639417104.2653282-67262-100139011685712/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/Users/jgspratt/.ansible/tmp/ansible-tmp-1639417104.2653282-67262-100139011685712/AnsiballZ_panos_custom_url_category.py", line 102, in <module>
    _ansiballz_main()
  File "/Users/jgspratt/.ansible/tmp/ansible-tmp-1639417104.2653282-67262-100139011685712/AnsiballZ_panos_custom_url_category.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/Users/jgspratt/.ansible/tmp/ansible-tmp-1639417104.2653282-67262-100139011685712/AnsiballZ_panos_custom_url_category.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.paloaltonetworks.panos.plugins.modules.panos_custom_url_category', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 210, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/var/folders/h9/w3s8_3091s58lm8xbnbrp2m80000gn/T/ansible_panos_custom_url_category_payload_fv3d684t/ansible_panos_custom_url_category_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_custom_url_category.py", line 151, in <module>
  File "/var/folders/h9/w3s8_3091s58lm8xbnbrp2m80000gn/T/ansible_panos_custom_url_category_payload_fv3d684t/ansible_panos_custom_url_category_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_custom_url_category.py", line 143, in main
  File "/usr/local/lib/python3.9/site-packages/pandevice/base.py", line 2206, in __init__
    raise ValueError('No param "{0}" exists'.format(name))
ValueError: No param "type" exists
fatal: [localhost]: FAILED! => {
    "changed": false,
    "rc": 1
}

MSG:

MODULE FAILURE
See stdout/stderr for the exact error


MODULE_STDERR:

Traceback (most recent call last):
  File "/Users/jgspratt/.ansible/tmp/ansible-tmp-1639417104.2653282-67262-100139011685712/AnsiballZ_panos_custom_url_category.py", line 102, in <module>
    _ansiballz_main()
  File "/Users/jgspratt/.ansible/tmp/ansible-tmp-1639417104.2653282-67262-100139011685712/AnsiballZ_panos_custom_url_category.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/Users/jgspratt/.ansible/tmp/ansible-tmp-1639417104.2653282-67262-100139011685712/AnsiballZ_panos_custom_url_category.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.paloaltonetworks.panos.plugins.modules.panos_custom_url_category', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 210, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/var/folders/h9/w3s8_3091s58lm8xbnbrp2m80000gn/T/ansible_panos_custom_url_category_payload_fv3d684t/ansible_panos_custom_url_category_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_custom_url_category.py", line 151, in <module>
  File "/var/folders/h9/w3s8_3091s58lm8xbnbrp2m80000gn/T/ansible_panos_custom_url_category_payload_fv3d684t/ansible_panos_custom_url_category_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_custom_url_category.py", line 143, in main
  File "/usr/local/lib/python3.9/site-packages/pandevice/base.py", line 2206, in __init__
    raise ValueError('No param "{0}" exists'.format(name))
ValueError: No param "type" exists


PLAY RECAP ********************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```

**Comment by jgspratt** [comment]
I initially tried it without the `type: URL List` but added it in to see if it would help.

**Comment by jgspratt** [comment]
Our expert told me I need to "upgrade from pandevice and use pan-os-python instead".  This should be fixed in the documentation if he is correct.

According to the documentation on https://paloaltonetworks.github.io/pan-os-ansible/modules/panos_custom_url_category.html :

> Requirements
> The below requirements are needed on the host that executes this module.
> pan-python can be obtained from PyPI https://pypi.python.org/pypi/pan-python
> pandevice can be obtained from PyPI https://pypi.python.org/pypi/pandevice

```
# pip3 install pan-python==
ERROR: Could not find a version that satisfies the requirement pan-python== (from versions: 0.3.0, 0.4.0, 0.5.0, 0.6.0, 0.7.0, 0.8.0, 0.9.0, 0.9.1, 0.10.0, 0.11.0, 0.12.0, 0.13.0, 0.14.0, 0.15.0, 0.16.0)
ERROR: No matching distribution found for pan-python==
```

```
# pip3 install pandevice==
ERROR: Could not find a version that satisfies the requirement pandevice== (from versions: 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.4.0, 0.4.1, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.6, 0.7.0, 0.8.0, 0.9.0, 0.9.1, 0.10.0, 0.11.0, 0.11.1, 0.12.0, 0.13.0, 0.14.0)
ERROR: No matching distribution found for pandevice==
```

**Comment by jgspratt** [comment]
After performing that upgrade, I have a different error message: `URLError: reason: [Errno 8] nodename nor servname provided, or not known`

```
# pip3 install pan-os-python
Collecting pan-os-python
  Downloading pan_os_python-1.6.0-py2.py3-none-any.whl (135 kB)
     |████████████████████████████████| 135 kB 4.3 MB/s
Requirement already satisfied: pan-python<0.17.0,>=0.16.0 in /usr/local/lib/python3.9/site-packages (from pan-os-python) (0.16.0)
Installing collected packages: pan-os-python
Successfully installed pan-os-python-1.6.0
```

```
TASK [Create test URL category] ***************************************************************************************
task path: /Users/jgspratt/git/jgs/lowside/scratch/ansible-test/palo.yml:15
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: jgspratt
<127.0.0.1> EXEC /bin/sh -c 'echo ~jgspratt && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/jgspratt/.ansible/tmp `"&& mkdir "` echo /Users/jgspratt/.ansible/tmp/ansible-tmp-1639702933.121002-42848-259613145567888 `" && echo ansible-tmp-1639702933.121002-42848-259613145567888="` echo /Users/jgspratt/.ansible/tmp/ansible-tmp-1639702933.121002-42848-259613145567888 `" ) && sleep 0'
Using module file /Users/jgspratt/.ansible/collections/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_custom_url_category.py
<127.0.0.1> PUT /Users/jgspratt/.ansible/tmp/ansible-local-428419nqbmhbx/tmpd5qngu1v TO /Users/jgspratt/.ansible/tmp/ansible-tmp-1639702933.121002-42848-259613145567888/AnsiballZ_panos_custom_url_category.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /Users/jgspratt/.ansible/tmp/ansible-tmp-1639702933.121002-42848-259613145567888/ /Users/jgspratt/.ansible/tmp/ansible-tmp-1639702933.121002-42848-259613145567888/AnsiballZ_panos_custom_url_category.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/local/opt/python@3.9/bin/python3.9 /Users/jgspratt/.ansible/tmp/ansible-tmp-1639702933.121002-42848-259613145567888/AnsiballZ_panos_custom_url_category.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /Users/jgspratt/.ansible/tmp/ansible-tmp-1639702933.121002-42848-259613145567888/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/var/folders/h9/w3s8_3091s58lm8xbnbrp2m80000gn/T/ansible_panos_custom_url_category_payload_ret6l5kc/ansible_panos_custom_url_category_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/module_utils/panos.py", line 186, in get_pandevice_parent
    self.device = PanDevice.create_from_device(*pan_device_auth)
  File "/usr/local/lib/python3.9/site-packages/panos/base.py", line 3531, in create_from_device
    system_info = device.refresh_system_info()
  File "/usr/local/lib/python3.9/site-packages/panos/base.py", line 3992, in refresh_system_info
    system_info = self.show_system_info()
  File "/usr/local/lib/python3.9/site-packages/panos/base.py", line 3948, in show_system_info
    root = self.xapi.op(cmd="show system info", cmd_xml=True)
  File "/usr/local/lib/python3.9/site-packages/panos/base.py", line 3783, in xapi
    self._xapi_private = self.generate_xapi()
  File "/usr/local/lib/python3.9/site-packages/panos/base.py", line 3849, in generate_xapi
    "api_key": self.api_key,
  File "/usr/local/lib/python3.9/site-packages/panos/base.py", line 3777, in api_key
    self._api_key = self._retrieve_api_key()
  File "/usr/local/lib/python3.9/site-packages/panos/base.py", line 3936, in _retrieve_api_key
    xapi.keygen(retry_on_peer=False)
  File "/usr/local/lib/python3.9/site-packages/panos/base.py", line 3680, in method
    raise the_exception
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "api_key": null,
            "description": "test-api-list",
            "device_group": "shared",
            "ip_address": null,
            "name": "test-api-list",
            "password": null,
            "port": 443,
            "provider": {
                "api_key": null,
                "ip_address": "[REDACTED]",
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "port": 443,
                "serial_number": null,
                "username": "admin"
            },
            "state": "present",
            "type": "URL List",
            "url_value": [
                "www.example.com",
                "www2.example.com"
            ],
            "username": "admin",
            "vsys": "vsys1"
        }
    }
}

MSG:

Failed connection: URLError: reason: [Errno 8] nodename nor servname provided, or not known

PLAY RECAP *******************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

**Comment by shinmog** [comment]
I've updated `panos_custom_url_category` to have a minimum pan-os-python version check of 1.5 so other will not have the same issue you originally encountered.

As for the error, that's a `URLError` error, which is making me wonder if you have the IP / hostname incorrect or something...?  Getting a `URLError` tho, you would theoretically get the same error just using `cURL`, much less ansible.

**Comment by jamesholland-uk** [comment]
I can't replicate the error with the task you defined:
```
---
- name: URL category test
  hosts: '{{ target | default("host_labfw") }}'
  connection: local

  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ username | default(omit) }}"
      password: "{{ password | default(omit) }}"
      api_key: "{{ api_key | default(omit) }}"

  tasks:
    - name: Create test URL category
      paloaltonetworks.panos.panos_custom_url_category:
        type: URL List
        provider: "{{ device }}"
        name: test-api-list
        description: test-api-list
        url_value:
          - www.example.com
          - www2.example.com
```
Results:
```
PLAY [URL category test] ********************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************
ok: [host_labfw]

TASK [Create test URL category] **************************************************************************************************************************************
changed: [host_labfw]

PLAY RECAP ***********************************************************************************************************************************************************
host_labfw                 : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```
Environment:
ansible core 2.13.1
python 3.10.4
pan-os-python 1.8.1
pan-os-ansible 2.13.2

Let's close this one for now, but please reopen if any further issues occur.
