### ISSUE TITLE
Unable to import certificate using panos_import module AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'

### ISSUE THREAD

**Issue by dpflick** [PaloAltoNetworks/pan-os-ansible#435]
System:
ansible [core 2.13.9]
  config file = /home/devops/onshore-devops/ansible.cfg
  configured module search path = ['/home/devops/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules', '/home/devops/onshore-devops/modules']
  ansible python module location = /home/devops/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/devops/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/devops/.local/bin/ansible
  python version = 3.8.10 (default, Mar 13 2023, 10:26:41) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = True

paloaltonetworks.panos version 2.16.0

Task:
- name: IMPORT EXISTING FORWARD TRUST CERTIFICATE WITH KEYS
  paloaltonetworks.panos.panos_import:
    provider: '{{ pancredentials }}'
    category: 'certificate'
    certificate_name: 'forward-trust'
    format: pem
    passphrase: '{{ network_enable_password }}'
    filename: '{{ ansible_inventory_sources[0] }}/external_files/certificates/forward-trust-private.pem'

ERROR:
TASK [panos_decrypt_certificate : IMPORT EXISTING FORWARD TRUST CERTIFICATE WITH KEYS] *********************************************************************
task path: /home/devops/onshore-devops/roles/panos_decrypt_certificate/tasks/main.yml:21
<12.244.27.174> ESTABLISH LOCAL CONNECTION FOR USER: devops
<12.244.27.174> EXEC /bin/sh -c 'echo ~devops && sleep 0'
<12.244.27.174> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/devops/.ansible/tmp `"&& mkdir "` echo /home/devops/.ansible/tmp/ansible-tmp-1683922196.879979-28163-192585377250709 `" && echo ansible-tmp-1683922196.879979-28163-192585377250709="` echo /home/devops/.ansible/tmp/ansible-tmp-1683922196.879979-28163-192585377250709 `" ) && sleep 0'
<bexar-brooks-vpnfw1-pri-ext> Attempting python interpreter discovery
<12.244.27.174> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'python3.10'"'"'; command -v '"'"'python3.9'"'"'; command -v '"'"'python3.8'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<12.244.27.174> EXEC /bin/sh -c '/usr/bin/python3.8 && sleep 0'
Using module file /home/devops/.ansible/collections/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_import.py
<12.244.27.174> PUT /home/devops/.ansible/tmp/ansible-local-28087015fw74k/tmpjayhoww9 TO /home/devops/.ansible/tmp/ansible-tmp-1683922196.879979-28163-192585377250709/AnsiballZ_panos_import.py
<12.244.27.174> EXEC /bin/sh -c 'chmod u+x /home/devops/.ansible/tmp/ansible-tmp-1683922196.879979-28163-192585377250709/ /home/devops/.ansible/tmp/ansible-tmp-1683922196.879979-28163-192585377250709/AnsiballZ_panos_import.py && sleep 0'
<12.244.27.174> EXEC /bin/sh -c '/usr/bin/python3 /home/devops/.ansible/tmp/ansible-tmp-1683922196.879979-28163-192585377250709/AnsiballZ_panos_import.py && sleep 0'
<12.244.27.174> EXEC /bin/sh -c 'rm -f -r /home/devops/.ansible/tmp/ansible-tmp-1683922196.879979-28163-192585377250709/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/devops/.ansible/tmp/ansible-tmp-1683922196.879979-28163-192585377250709/AnsiballZ_panos_import.py", line 107, in <module>
    _ansiballz_main()
  File "/home/devops/.ansible/tmp/ansible-tmp-1683922196.879979-28163-192585377250709/AnsiballZ_panos_import.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/devops/.ansible/tmp/ansible-tmp-1683922196.879979-28163-192585377250709/AnsiballZ_panos_import.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.paloaltonetworks.panos.plugins.modules.panos_import', init_globals=dict(_module_fqn='ansible_collections.paloaltonetworks.panos.plugins.modules.panos_import', _modlib_path=modlib_path),
  File "/usr/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_paloaltonetworks.panos.panos_import_payload_26silloy/ansible_paloaltonetworks.panos.panos_import_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_import.py", line 201, in <module>
  File "/usr/lib/python3/dist-packages/requests/__init__.py", line 95, in <module>
    from urllib3.contrib import pyopenssl
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1553, in <module>
    class X509StoreFlags(object):
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1573, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 72, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 32, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 12, in <module>
    import os, glob, subprocess, os.path, time, pwd, sys, requests_unixsocket
  File "/usr/lib/python3/dist-packages/requests_unixsocket/__init__.py", line 1, in <module>
    import requests
  File "/usr/lib/python3/dist-packages/requests/__init__.py", line 95, in <module>
    from urllib3.contrib import pyopenssl
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1553, in <module>
    class X509StoreFlags(object):
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1573, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'

Original exception was:
Traceback (most recent call last):
  File "/home/devops/.ansible/tmp/ansible-tmp-1683922196.879979-28163-192585377250709/AnsiballZ_panos_import.py", line 107, in <module>
    _ansiballz_main()
  File "/home/devops/.ansible/tmp/ansible-tmp-1683922196.879979-28163-192585377250709/AnsiballZ_panos_import.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/devops/.ansible/tmp/ansible-tmp-1683922196.879979-28163-192585377250709/AnsiballZ_panos_import.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.paloaltonetworks.panos.plugins.modules.panos_import', init_globals=dict(_module_fqn='ansible_collections.paloaltonetworks.panos.plugins.modules.panos_import', _modlib_path=modlib_path),
  File "/usr/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_paloaltonetworks.panos.panos_import_payload_26silloy/ansible_paloaltonetworks.panos.panos_import_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_import.py", line 201, in <module>
  File "/usr/lib/python3/dist-packages/requests/__init__.py", line 95, in <module>
    from urllib3.contrib import pyopenssl
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1553, in <module>
    class X509StoreFlags(object):
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1573, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
fatal: [bexar-brooks-vpnfw1-pri-ext]: FAILED! => changed=false 
  ansible_facts:
    discovered_interpreter_python: /usr/bin/python3
  module_stderr: |-
    Traceback (most recent call last):
      File "/home/devops/.ansible/tmp/ansible-tmp-1683922196.879979-28163-192585377250709/AnsiballZ_panos_import.py", line 107, in <module>
        _ansiballz_main()
      File "/home/devops/.ansible/tmp/ansible-tmp-1683922196.879979-28163-192585377250709/AnsiballZ_panos_import.py", line 99, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/home/devops/.ansible/tmp/ansible-tmp-1683922196.879979-28163-192585377250709/AnsiballZ_panos_import.py", line 47, in invoke_module
        runpy.run_module(mod_name='ansible_collections.paloaltonetworks.panos.plugins.modules.panos_import', init_globals=dict(_module_fqn='ansible_collections.paloaltonetworks.panos.plugins.modules.panos_import', _modlib_path=modlib_path),
      File "/usr/lib/python3.8/runpy.py", line 207, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_paloaltonetworks.panos.panos_import_payload_26silloy/ansible_paloaltonetworks.panos.panos_import_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_import.py", line 201, in <module>
      File "/usr/lib/python3/dist-packages/requests/__init__.py", line 95, in <module>
        from urllib3.contrib import pyopenssl
      File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
        import OpenSSL.SSL
      File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
        from OpenSSL import crypto, SSL
      File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1553, in <module>
        class X509StoreFlags(object):
      File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1573, in X509StoreFlags
        CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
    AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
    Error in sys.excepthook:
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 72, in apport_excepthook
        from apport.fileutils import likely_packaged, get_recent_crashes
      File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
        from apport.report import Report
      File "/usr/lib/python3/dist-packages/apport/report.py", line 32, in <module>
        import apport.fileutils
      File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 12, in <module>
        import os, glob, subprocess, os.path, time, pwd, sys, requests_unixsocket
      File "/usr/lib/python3/dist-packages/requests_unixsocket/__init__.py", line 1, in <module>
        import requests
      File "/usr/lib/python3/dist-packages/requests/__init__.py", line 95, in <module>
        from urllib3.contrib import pyopenssl
      File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
        import OpenSSL.SSL
      File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
        from OpenSSL import crypto, SSL
      File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1553, in <module>
        class X509StoreFlags(object):
      File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1573, in X509StoreFlags
        CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
    AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
  
    Original exception was:
    Traceback (most recent call last):
      File "/home/devops/.ansible/tmp/ansible-tmp-1683922196.879979-28163-192585377250709/AnsiballZ_panos_import.py", line 107, in <module>
        _ansiballz_main()
      File "/home/devops/.ansible/tmp/ansible-tmp-1683922196.879979-28163-192585377250709/AnsiballZ_panos_import.py", line 99, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/home/devops/.ansible/tmp/ansible-tmp-1683922196.879979-28163-192585377250709/AnsiballZ_panos_import.py", line 47, in invoke_module
        runpy.run_module(mod_name='ansible_collections.paloaltonetworks.panos.plugins.modules.panos_import', init_globals=dict(_module_fqn='ansible_collections.paloaltonetworks.panos.plugins.modules.panos_import', _modlib_path=modlib_path),
      File "/usr/lib/python3.8/runpy.py", line 207, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_paloaltonetworks.panos.panos_import_payload_26silloy/ansible_paloaltonetworks.panos.panos_import_payload.zip/ansible_collections/paloaltonetworks/panos/plugins/modules/panos_import.py", line 201, in <module>
      File "/usr/lib/python3/dist-packages/requests/__init__.py", line 95, in <module>
        from urllib3.contrib import pyopenssl
      File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
        import OpenSSL.SSL
      File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
        from OpenSSL import crypto, SSL
      File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1553, in <module>
        class X509StoreFlags(object):
      File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1573, in X509StoreFlags
        CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
    AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1

**Comment by jamesholland-uk** [comment]
Hi @dpflick, currently I an not able to reproduce this issue, so I am unable to look at a fix. Can you share any more about what is in the `forward-trust-private.pem` file? Just the cert, or cert and private key? Or is the private key in a separate file? That might help me replicate the scenario more accurately.

I don't enjoy referring to StackOverflow, but have you checked some of the suggestions in thread like [this](https://stackoverflow.com/questions/73830524/attributeerror-module-lib-has-no-attribute-x509-v-flag-cb-issuer-check) which walk through fixing the currently installed version of Python etc? As things stand, I am not sure this is an issue with the `panos_import` module itself, but if you are still experiencing this issue, please come back to us with more info based on the questions above and having looked at the linked thread. Thanks :-)

**Comment by dpflick** [comment]
The forward trust private is the cert and key used for decryption.  I will check the link.  Thanks

Sent from Nine<http://www.9folders.com/>

________________________________

**Comment by jamesholland-uk** [comment]
Thanks for the update. For cert AND key, then you want `category: 'keypair'` in the task instead of `category: 'certificate'`. Although I think the python issue might still persist even after that change to the task. Please let us know how you get on.

**Comment by jamesholland-uk** [comment]
If a problem persists, please reopen this issue
